export const STEPS = [
  {
    id: 'pathway',
    title: '確認申請途徑',
    subtitle: '州提名 vs 家庭擔保',
    duration: '1–2 週研究',
    description: '491 簽證有兩條途徑：州/領地政府提名，或者合資格親屬擔保。你需要先決定走邊條路，因為後續步驟會唔同。',
    tasks: [
      '了解州政府提名途徑（最常見）',
      '了解家庭擔保途徑（需要有親屬住偏遠地區）',
      '確認自己年齡未滿 45 歲（邀請時）',
      '確認提名職業喺合適嘅職業清單上',
      '決定目標州份或確認擔保人資格',
    ],
    links: [
      { label: '491 官方頁面', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-provisional-491' },
      { label: '職業清單搜尋', url: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skill-occupation-list' },
    ],
  },
  {
    id: 'occupation',
    title: '確認提名職業',
    subtitle: 'ANZSCO 職業代碼',
    duration: '1 週',
    description: '你嘅職業必須喺澳洲技術職業清單（MLTSSL、STSOL 或 ROL）上，而且各州可能有自己嘅優先職業清單。',
    tasks: [
      '喺 Home Affairs 網站搜尋你嘅 ANZSCO 職業代碼',
      '確認職業喺邊個清單上（MLTSSL / STSOL / ROL）',
      '查目標州份嘅優先職業清單',
      '確認你嘅學歷同工作經驗符合該職業要求',
      '記低你嘅 ANZSCO code（例如 261313 = Software Engineer）',
    ],
    links: [
      { label: '職業清單', url: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skill-occupation-list' },
      { label: 'ANZSCO 搜尋', url: 'https://www.abs.gov.au/statistics/classifications/anzsco-australian-and-new-zealand-standard-classification-occupations' },
    ],
  },
  {
    id: 'skills-assessment',
    title: '職業評估（Skills Assessment）',
    subtitle: '最重要嘅前置步驟之一',
    duration: '6–12 週',
    description: '你需要向相關評估機構申請 Positive Skills Assessment。評估結果有效期通常 3 年。唔同職業由唔同機構負責（例如 ACS、EA、VETASSESS、CPA 等）。',
    tasks: [
      '確認你職業對應嘅評估機構',
      '準備學歷證書同成績單（可能需要 NAATI 認證翻譯）',
      '準備工作證明信（Employment Reference Letters）',
      '撰寫詳細嘅職責描述（Duty Statement）',
      '提交評估申請並繳費',
      '收到 Positive Outcome 結果信',
    ],
    links: [
      { label: '評估機構列表', url: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-assessment' },
      { label: 'ACS（IT 類）', url: 'https://www.acs.org.au/' },
      { label: 'VETASSESS', url: 'https://www.vetassess.com.au/' },
    ],
  },
  {
    id: 'english',
    title: '英文考試',
    subtitle: 'IELTS / PTE / TOEFL / OET / CAE',
    duration: '2–4 週準備 + 考試',
    description: '最低要求係 Competent English（IELTS 6.0 各項）。但為咗競爭力，建議考到 Proficient（7.0，+10 分）或 Superior（8.0，+20 分）。',
    tasks: [
      '選擇考試類型（PTE 通常出分快，好多申請人用）',
      '報名考試',
      '準備並應考',
      '收到成績單（有效期 3 年）',
      '確認分數達到目標（Competent / Proficient / Superior）',
      '如果未達標，規劃重考',
    ],
    links: [
      { label: '英文要求詳情', url: 'https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language' },
      { label: 'IELTS', url: 'https://www.ielts.org/' },
      { label: 'PTE Academic', url: 'https://www.pearsonpte.com/' },
    ],
  },
  {
    id: 'points',
    title: '計算移民分數',
    subtitle: '最低 65 分 + 州提名 15 分',
    duration: '1 日',
    description: '用本分數計算器計算你嘅分數。EOI 最低需要 65 分，但實際邀請分數通常更高，視乎州份同職業而定。',
    tasks: [
      '用網站分數計算器計算你嘅分數',
      '確認達到最低 65 分（未計州提名）',
      '如果分數唔夠，規劃提升方案（考更高英文、累積工作經驗等）',
      '記錄你嘅分數明細，EOI 時需要填寫',
    ],
    links: [
      { label: '官方分數表', url: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skillselect/points-table' },
    ],
  },
  {
    id: 'eoi',
    title: '提交 EOI（Expression of Interest）',
    subtitle: 'SkillSelect 系統',
    duration: '1–2 小時',
    description: '喺 SkillSelect 提交 EOI，呢個唔係正式申請，而係讓州政府同內政部知道你嘅意向。EOI 有效期 2 年。',
    tasks: [
      '喺 ImmiAccount 建立帳戶',
      '進入 SkillSelect 提交 EOI',
      '填寫提名職業、分數、工作經驗、學歷',
      '上傳英文成績同職業評估結果',
      '選擇感興趣嘅州份（可多選）',
      '提交 EOI 並記低 EOI reference number',
    ],
    links: [
      { label: 'ImmiAccount', url: 'https://online.immi.gov.au/lusc/login' },
      { label: 'SkillSelect 指南', url: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skillselect' },
    ],
  },
  {
    id: 'state-nomination',
    title: '申請州政府提名',
    subtitle: 'ROI → 邀請 → 提名',
    duration: '數週至數月',
    description: '向目標州提交 Registration of Interest（ROI）。每個州有自己嘅系統同要求。被邀請後提交完整提名申請。',
    tasks: [
      '研究目標州嘅 491 提名要求同職業清單',
      '喺州政府移民網站建立帳戶',
      '提交 ROI（需要 EOI number）',
      '等待州政府邀請（invitation round）',
      '收到邀請後提交完整提名申請',
      '準備州提名所需額外文件（Commitment Statement 等）',
      '收到州提名批准（Nomination Approval）',
    ],
    links: [
      { label: '南澳 Migration SA', url: 'https://www.migration.sa.gov.au/' },
      { label: '維州 Live in Melbourne', url: 'https://liveinmelbourne.vic.gov.au/migrate' },
      { label: '西澳 Migration WA', url: 'https://migration.wa.gov.au/' },
      { label: '塔州 Migration TAS', url: 'https://www.migration.tas.gov.au/' },
    ],
  },
  {
    id: 'invitation',
    title: '收到 ITA 邀請',
    subtitle: 'Invitation to Apply — 60 日限期！',
    duration: '60 日內行動',
    description: '州提名獲批後，內政部會透過 ImmiAccount 發出 Invitation to Apply（ITA）。你有 60 日內遞交完整簽證申請，錯過就冇咗！',
    tasks: [
      '檢查 ImmiAccount 收到 ITA 通知',
      '確認 60 日截止日期（記低喺日曆！）',
      '立即開始準備所有簽證申請文件',
      '預約體檢（Health Examination）',
      '申請良民證（Police Certificate）— 香港、澳洲、所有住過 12 個月以上嘅國家',
      '準備所有證明文件嘅認證副本',
    ],
    links: [
      { label: 'ImmiAccount', url: 'https://online.immi.gov.au/lusc/login' },
      { label: '體檢要求', url: 'https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/health' },
      { label: '良民證要求', url: 'https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/character' },
    ],
  },
  {
    id: 'visa-lodgement',
    title: '遞交 491 簽證申請',
    subtitle: 'ImmiAccount 正式申請',
    duration: '建議第 1 日就遞交',
    description: '透過 ImmiAccount 遞交完整嘅 491 簽證申請，連同所有支持文件。簽證費主申請人約 AUD $4,640（2026）。',
    tasks: [
      '喺 ImmiAccount 開始 491 簽證申請',
      '填寫所有表格（包括 Form 80 等）',
      '上傳所有支持文件',
      '繳交簽證申請費',
      '提交申請並記低 Transaction Reference Number（TRN）',
      '如果有配偶/子女，一併申請',
    ],
    links: [
      { label: '簽證費用', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/fees-and-charges/current-visa-pricing' },
      { label: 'Form 80', url: 'https://immi.homeaffairs.gov.au/form-listing/forms/80.pdf' },
    ],
  },
  {
    id: 'health-character',
    title: '體檢與良民證',
    subtitle: 'Health & Character Requirements',
    duration: '2–4 週',
    description: '所有申請人都需要通過體檢同品格審查。建議收到 ITA 後立即開始，因為良民證可能需要幾星期。',
    tasks: [
      '預約 Bupa / Medibank 等指定體檢中心（用 HAP ID）',
      '完成體檢（胸肺 X 光、血液檢查等）',
      '向香港警務處申請良民證（Certificate of No Criminal Conviction）',
      '向所有住過 12 個月以上嘅國家申請良民證',
      '確保良民證喺有效期內（通常 12 個月）',
      '上傳或等內政部索取',
    ],
    links: [
      { label: '香港良民證', url: 'https://www.police.gov.hk/ppp_en/11/14.html' },
      { label: '澳洲體檢安排', url: 'https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/health/examinations' },
    ],
  },
  {
    id: 'waiting',
    title: '等待簽證審批',
    subtitle: 'Processing Time',
    duration: '數月至一年+',
    description: '遞交後進入審批隊列。期間可能收到 Request for Further Information（RFI），要及時回覆。可以喺 ImmiAccount 查看進度。',
    tasks: [
      '定期檢查 ImmiAccount 申請狀態',
      '及時回覆任何 RFI（補充資料要求）',
      '保持護照有效期',
      '唔好做可能影響簽證嘅事（如提供虛假資料）',
      '考慮購買澳洲醫療保險（OVHC）為登陸做準備',
      '開始規劃搬遷（住宿、工作等）',
    ],
    links: [
      { label: '審批時間', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-processing-times' },
    ],
  },
  {
    id: 'grant',
    title: '簽證獲批 & 登陸',
    subtitle: 'Visa Grant — 開始新生活',
    duration: '持續',
    description: '491 簽證獲批！你會收到 Grant Notification。之後可以登陸澳洲，開始你嘅偏遠地區新生活，並為 3 年後嘅 191 永居做準備。',
    tasks: [
      '收到 Visa Grant Notification（檢查所有條件）',
      '確認首次入境期限（通常係體檢/良民證有效期內）',
      '安排搬遷（機票、住宿、銀行戶口等）',
      '登陸澳洲並入住偏遠地區',
      '申請 TFN（稅號）、Medicare、銀行戶口',
      '開始工作並保留收入記錄（為 191 做準備）',
      '記錄居住地址同時間（為 191 做準備）',
    ],
    links: [
      { label: '191 永居簽證', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/permanent-residence-skilled-regional-191' },
      { label: '搬遷指南', url: 'https://www.australia.gov.au/visas-and-migration' },
    ],
  },
];

export const DOCUMENTS = [
  {
    category: '身份證明',
    items: [
      '有效護照（所有頁面彩色掃描）',
      '出生證明（需 NAATI 認證翻譯）',
      '身份證（如有）',
      '護照尺寸照片（近期）',
      '改名證明（如有）',
    ],
  },
  {
    category: '職業評估',
    items: [
      'Positive Skills Assessment 結果信',
      '學歷證書及成績單（認證翻譯）',
      '工作證明信（Employment Reference Letters）',
      '職責描述（Duty Statement / Position Description）',
      '組織架構圖（如評估機構要求）',
      'CV / Resume',
    ],
  },
  {
    category: '英文成績',
    items: [
      'IELTS / PTE / TOEFL 成績單',
      '確認成績單喺 3 年有效期內',
    ],
  },
  {
    category: '工作經驗證明',
    items: [
      '僱主信（公司抬頭、職位、日期、職責、簽名）',
      '糧單（Payslips）',
      '稅單 / 強積金紀錄',
      '勞動合同',
    ],
  },
  {
    category: '健康與品格',
    items: [
      '體檢報告（由指定醫生完成）',
      '香港良民證（Certificate of No Criminal Conviction）',
      '所有住過 12 個月以上國家嘅良民證',
      'Form 80（Personal Particulars for Assessment）',
      'Form 1221（Additional Information，如適用）',
    ],
  },
  {
    category: '家庭成員（如適用）',
    items: [
      '結婚證書 / 事實婚姻證明',
      '配偶護照同出生證明',
      '子女出生證明同護照',
      '配偶英文成績（如申報配偶加分）',
      '配偶職業評估（如申報配偶技能加分）',
    ],
  },
  {
    category: '州提名相關',
    items: [
      '州提名批准信（Nomination Approval Letter）',
      'Commitment Statement（承諾書）',
      '州提名申請時提交嘅所有文件',
      'EOI reference number',
    ],
  },
];

export const STATES = [
  {
    name: '南澳 South Australia',
    abbr: 'SA',
    notes: '491 邀請較活躍，ICT 職業近年主要透過 491 途徑。阿德萊德屬偏遠地區。',
    url: 'https://www.migration.sa.gov.au/',
  },
  {
    name: '塔斯曼尼亞 Tasmania',
    abbr: 'TAS',
    notes: '全州都係偏遠地區。提名要求相對靈活，適合願意住小城市嘅申請人。',
    url: 'https://www.migration.tas.gov.au/',
  },
  {
    name: '北領地 Northern Territory',
    abbr: 'NT',
    notes: '達爾文屬偏遠地區。人口少，競爭可能較低，但就業機會要事先研究。',
    url: 'https://theterritory.com.au/migrate',
  },
  {
    name: '西澳 Western Australia',
    abbr: 'WA',
    notes: '珀斯以外地區屬偏遠。近年提名政策有調整，要留意最新職業清單。',
    url: 'https://migration.wa.gov.au/',
  },
  {
    name: '維多利亞 Victoria',
    abbr: 'VIC',
    notes: '墨爾本以外地區（如 Geelong、Ballarat）屬偏遠。競爭較激烈。',
    url: 'https://liveinmelbourne.vic.gov.au/migrate',
  },
  {
    name: '新南威爾斯 New South Wales',
    abbr: 'NSW',
    notes: '悉尼以外地區（如 Newcastle、Wollongong）屬偏遠。要求通常較高。',
    url: 'https://www.nsw.gov.au/visas-and-migration/skilled-visas',
  },
  {
    name: '昆士蘭 Queensland',
    abbr: 'QLD',
    notes: '布里斯班、黃金海岸以外地區屬偏遠（如 Townsville、Cairns）。',
    url: 'https://migration.qld.gov.au/',
  },
  {
    name: '首都領地 ACT',
    abbr: 'ACT',
    notes: '堪培拉唔屬偏遠地區，但 ACT 有自己嘅提名計劃，要查最新政策。',
    url: 'https://www.canberrayourfuture.com.au/',
  },
];

export const STORAGE_KEY = 'visa491-tracker-v1';
